name = "kpl-guessr-frontend"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[assets]
directory = "build"

[env.production]
name = "kpl-guessr-frontend-prod"

[env.staging]
name = "kpl-guessr-frontend-staging"
